from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
import math

# Benchmark Configuration
# Target Qubits: 100
# Target Gates: 200
# Target Mid-Circuit Measurements: 10

q = QuantumRegister(100, 'q')
c = ClassicalRegister(10, 'c')
circ = QuantumCircuit(q, c)

# --- Initialization ---
circ.cx(q[9], q[67])
circ.s(q[8])
circ.s(q[4])
circ.t(q[44])
circ.x(q[36])
circ.x(q[15])
circ.x(q[61])
circ.x(q[47])
circ.cz(q[79], q[15])
circ.x(q[52])
circ.h(q[78])
circ.cx(q[50], q[29])
circ.h(q[3])
circ.x(q[10])
circ.x(q[57])
circ.t(q[89])
circ.cx(q[19], q[82])
circ.cx(q[95], q[68])
circ.cx(q[11], q[96])
circ.rz(math.pi/2, q[73])

# --- SQC Block: While Loop (Controlled by c[0]) ---
with circ.while_loop((c[0], 0)):
    # Loop Body
    circ.h(q[10])
    circ.s(q[21])
    circ.rz(math.pi/2, q[22])
    circ.cz(q[31], q[75])
    circ.s(q[29])
    circ.rz(math.pi/2, q[50])
    circ.s(q[69])
    circ.x(q[95])
    circ.cx(q[37], q[50])
    circ.h(q[91])
    circ.x(q[66])
    circ.cx(q[99], q[55])
    circ.t(q[38])
    circ.rz(math.pi/2, q[68])
    circ.cz(q[57], q[45])
    circ.rz(math.pi/2, q[44])
    circ.s(q[57])
    # DQC: Mid-circuit measurement
    circ.measure(q[21], c[1])
    with circ.if_test((c[1], 1)):
        circ.s(q[98])
        circ.x(q[73])
    circ.cz(q[80], q[55])
    circ.x(q[22])
    circ.t(q[10])
    circ.cz(q[80], q[11])
    circ.rz(math.pi/2, q[78])
    circ.rz(math.pi/2, q[85])
    circ.x(q[41])
    circ.x(q[97])
    circ.s(q[42])
    circ.x(q[20])
    circ.cx(q[43], q[27])
    circ.cz(q[56], q[98])
    circ.rz(math.pi/2, q[53])
    circ.s(q[64])
    circ.s(q[93])
    circ.rz(math.pi/2, q[1])
    circ.x(q[7])
    # DQC: Mid-circuit measurement
    circ.measure(q[71], c[2])
    with circ.if_test((c[2], 1)):
        circ.h(q[81])
        circ.cx(q[95], q[17])
    circ.t(q[47])
    circ.rz(math.pi/2, q[3])
    circ.h(q[99])
    circ.t(q[95])
    circ.rz(math.pi/2, q[20])
    circ.h(q[40])
    circ.s(q[72])
    circ.s(q[14])
    circ.cx(q[52], q[31])
    circ.rz(math.pi/2, q[85])
    circ.x(q[96])
    circ.h(q[19])
    circ.h(q[76])
    circ.cx(q[83], q[28])
    circ.rz(math.pi/2, q[36])
    circ.s(q[68])
    circ.t(q[2])
    # DQC: Mid-circuit measurement
    circ.measure(q[99], c[3])
    with circ.if_test((c[3], 1)):
        circ.h(q[14])
        circ.cz(q[14], q[26])
    circ.s(q[65])
    circ.rz(math.pi/2, q[75])
    circ.x(q[52])
    circ.cz(q[44], q[96])
    circ.s(q[37])
    circ.cz(q[84], q[2])
    circ.h(q[3])
    circ.t(q[95])
    circ.x(q[78])
    circ.t(q[37])
    circ.t(q[44])
    circ.h(q[17])
    circ.s(q[10])
    circ.t(q[66])
    circ.cx(q[42], q[79])
    circ.s(q[90])
    circ.t(q[50])
    # DQC: Mid-circuit measurement
    circ.measure(q[8], c[4])
    with circ.if_test((c[4], 1)):
        circ.s(q[98])
        circ.x(q[85])
    circ.s(q[38])
    circ.rz(math.pi/2, q[98])
    circ.h(q[73])
    circ.cx(q[78], q[82])
    circ.x(q[97])
    circ.cx(q[30], q[99])
    circ.cz(q[35], q[92])
    circ.h(q[76])
    circ.cx(q[8], q[31])
    circ.s(q[86])
    circ.x(q[96])
    circ.rz(math.pi/2, q[16])
    circ.rz(math.pi/2, q[91])
    circ.rz(math.pi/2, q[69])
    circ.t(q[17])
    circ.s(q[6])
    circ.h(q[45])
    # DQC: Mid-circuit measurement
    circ.measure(q[29], c[5])
    with circ.if_test((c[5], 1)):
        circ.rz(math.pi/2, q[63])
        circ.cz(q[76], q[89])
    circ.x(q[16])
    circ.s(q[54])
    circ.cx(q[69], q[41])
    circ.x(q[78])
    circ.h(q[91])
    circ.cx(q[25], q[96])
    circ.x(q[16])
    circ.x(q[30])
    circ.h(q[3])
    circ.x(q[11])
    circ.t(q[96])
    circ.s(q[32])
    circ.s(q[55])
    circ.s(q[52])
    circ.x(q[56])
    circ.x(q[16])
    circ.cz(q[60], q[86])
    # DQC: Mid-circuit measurement
    circ.measure(q[17], c[6])
    with circ.if_test((c[6], 1)):
        circ.s(q[65])
        circ.t(q[54])
    circ.cx(q[95], q[30])
    circ.cx(q[38], q[73])
    circ.s(q[7])
    circ.cz(q[58], q[87])
    circ.h(q[18])
    circ.cx(q[61], q[46])
    circ.cz(q[38], q[35])
    circ.cz(q[11], q[41])
    circ.cx(q[28], q[46])
    circ.t(q[32])
    circ.x(q[85])
    circ.h(q[2])
    circ.rz(math.pi/2, q[62])
    circ.cx(q[77], q[22])
    circ.rz(math.pi/2, q[98])
    circ.h(q[77])
    circ.x(q[59])
    # DQC: Mid-circuit measurement
    circ.measure(q[82], c[7])
    with circ.if_test((c[7], 1)):
        circ.cz(q[37], q[44])
        circ.cz(q[75], q[5])
    circ.rz(math.pi/2, q[88])
    circ.x(q[34])
    circ.x(q[19])
    circ.t(q[14])
    circ.cx(q[50], q[79])
    circ.rz(math.pi/2, q[80])
    circ.rz(math.pi/2, q[51])
    circ.cz(q[93], q[98])
    circ.rz(math.pi/2, q[13])
    circ.h(q[20])
    circ.cx(q[45], q[1])
    circ.rz(math.pi/2, q[22])
    circ.t(q[35])
    circ.h(q[64])
    circ.cx(q[43], q[85])
    circ.rz(math.pi/2, q[97])
    circ.s(q[78])
    # DQC: Mid-circuit measurement
    circ.measure(q[72], c[8])
    with circ.if_test((c[8], 1)):
        circ.cz(q[53], q[51])
        circ.t(q[33])
    circ.t(q[94])
    circ.t(q[57])
    circ.x(q[5])
    circ.t(q[5])
    circ.t(q[59])
    circ.s(q[54])
    circ.t(q[26])
    circ.s(q[29])
    circ.t(q[62])
    circ.s(q[12])
    circ.cz(q[3], q[4])
    circ.t(q[72])
    circ.cz(q[29], q[2])
    circ.cx(q[30], q[2])
    circ.h(q[8])
    circ.cx(q[68], q[37])
    circ.t(q[29])
    # DQC: Mid-circuit measurement
    circ.measure(q[69], c[9])
    with circ.if_test((c[9], 1)):
        circ.x(q[12])
        circ.x(q[23])
    circ.rz(math.pi/2, q[32])
    circ.cx(q[42], q[38])
    circ.t(q[6])
    circ.t(q[4])
    circ.rz(math.pi/2, q[59])
    circ.t(q[95])
    circ.rz(math.pi/2, q[97])
    # Update Loop Condition (Must be FINAL op for q[0])
    # Ensure termination: Reset q[0] to |0> then apply H
    circ.reset(q[0])
    circ.h(q[0])
    circ.measure(q[0], c[0])

# Simulator Configuration by User
sim_mode = 'sample'
# No preset values needed for sample mode