import os
import sys
import subprocess
import time
import statistics
import re
import datetime

# ================= Configuration Area =================

# 1. Get absolute path of current script (exp/simulation)
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))

# 2. Project root directory (Assuming ../../)
PROJECT_ROOT = os.path.dirname(os.path.dirname(CURRENT_DIR))

# 3. Key file paths
GEN_SCRIPT = os.path.join(CURRENT_DIR, "gen_rqc.py")
RQC_DIR = os.path.join(CURRENT_DIR, "rqc")
DATA_DIR = os.path.join(CURRENT_DIR, "data")
LOG_FILE = os.path.join(DATA_DIR, "rqc.log")

# LaTeX output file (placed in project root)
TEX_FILE = os.path.join(PROJECT_ROOT, "rqc_result.tex")

# 4. [Important] Simulator Entry File Path
SIMULATOR_ENTRY = os.path.join(CURRENT_DIR, "exp_engine.py")

# 5. Experiment Parameters
PYTHON_EXEC = sys.executable
REPEAT_TIMES = 50  # How many sample runs per circuit
FIXED_QUBITS = 100

# Experiment Matrix: (Gates, Mid-Meas)
EXPERIMENTS = [
    (50, 5), (50, 10), (50, 20),
    (100, 5), (100, 10), (100, 20),
    (200, 5), (200, 10), (200, 20)
]

# ===========================================

def ensure_dirs():
    """Ensure necessary directories exist"""
    if not os.path.exists(RQC_DIR):
        os.makedirs(RQC_DIR)
    if not os.path.exists(DATA_DIR):
        os.makedirs(DATA_DIR)

def log_result(benchmark_name, run_id, status, value):
    """
    Write result to log file
    Status: SUCCESS, TIMEOUT, LOOPOUT, ERROR
    Value: Time (float) or Error Message (str)
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_line = f"[{timestamp}] {benchmark_name} | Run {run_id} | {status} | {value}\n"
    
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(log_line)

def parse_total_runtime(output_str):
    """
    Parse Total Runtime from exp_engine.py standard output.
    """
    match = re.search(r"Total Runtime\s*:\s*([\d\.]+)\s*s", output_str)
    if match:
        return float(match.group(1))
    return None

def check_loopout_error(output_str):
    """Check if output contains loop limit error"""
    if "Max iterations" in output_str:
        return True
    return False

def run_single_benchmark(benchmark_filename, run_id):
    """
    Run single benchmark and return (status, value)
    """
    rel_path = os.path.join("rqc", os.path.splitext(benchmark_filename)[0])
    
    try:
        cmd = [PYTHON_EXEC, SIMULATOR_ENTRY, rel_path]
        env = os.environ.copy()
        env["PYTHONPATH"] = PROJECT_ROOT + os.pathsep + env.get("PYTHONPATH", "")

        result = subprocess.run(
            cmd, 
            capture_output=True, 
            text=True, 
            timeout=600, # 10 minutes timeout
            env=env,
            cwd=CURRENT_DIR 
        )
        
        if result.returncode != 0:
            if check_loopout_error(result.stdout) or check_loopout_error(result.stderr):
                return "LOOPOUT", "Max iterations reached"
            err_msg = (result.stderr.strip() or result.stdout.strip()).replace("\n", " ")[:200]
            return "ERROR", err_msg
            
        if check_loopout_error(result.stdout):
            return "LOOPOUT", "Max iterations reached"

        time_val = parse_total_runtime(result.stdout)
        if time_val is None:
            return "ERROR", "Could not parse Total Runtime"
            
        return "SUCCESS", time_val

    except subprocess.TimeoutExpired:
        return "TIMEOUT", "Process timed out > 600s"
    except Exception as e:
        return "ERROR", str(e)

def calculate_stats(times):
    """
    Calculate Statistics: Median [Q1, Q3]
    """
    if not times:
        return 0.0, 0.0, 0.0
    
    times.sort()
    median = statistics.median(times)
    
    if len(times) >= 2:
        try:
            qs = statistics.quantiles(times, n=4)
            q1 = qs[0]
            q3 = qs[2]
        except AttributeError:
            mid = len(times) // 2
            q1 = statistics.median(times[:mid])
            q3 = statistics.median(times[mid + (len(times)%2):])
    else:
        q1 = times[0]
        q3 = times[0]
        
    return median, q1, q3

def write_latex_file(results):
    """Write results to .tex file in project root"""
    try:
        with open(TEX_FILE, "w", encoding="utf-8") as f:
            f.write(r"% Auto-generated by run_rqc_exp.py" + "\n")
            f.write(r"% Contains performance data for Random Quantum Circuits (RQC)" + "\n")
            f.write(r"\begin{table}[htbp]" + "\n")
            f.write(r"  \centering" + "\n")
            f.write(r"  \caption{Performance of QSeqSim on Random Quantum Circuits (100 Qubits). Time format: Median [Q1, Q3].}" + "\n")
            f.write(r"  \label{tab:rqc_results}" + "\n")
            f.write(r"  \begin{tabular}{lcccc}" + "\n")
            f.write(r"    \hline" + "\n")
            f.write(r"    Benchmark & Qubits & Gates & Mid-Meas & Total Time (s) \\ \hline" + "\n")
            
            for r in results:
                # Use LaTeX \scriptsize to shrink IQR font for better look
                line = f"    {r['name']} & {r['qubits']} & {r['gates']} & {r['meas']} & {r['median']:.3f} \\scriptsize{{[{r['q1']:.3f}, {r['q3']:.3f}]}} \\\\"
                f.write(line + "\n")
                
            f.write(r"    \hline" + "\n")
            f.write(r"  \end{tabular}" + "\n")
            f.write(r"\end{table}" + "\n")
        
        print(f"\n[Success] LaTeX table saved to: {TEX_FILE}")
        
    except Exception as e:
        print(f"\n[Error] Failed to write LaTeX file: {e}")

def main():
    ensure_dirs()
    
    # Initialize Log
    with open(LOG_FILE, "w", encoding="utf-8") as f:
        f.write("=== RQC Experiment Log ===\n")
        f.write("Format: [Timestamp] Benchmark | Run ID | Status | Value\n")

    if not os.path.exists(GEN_SCRIPT) or not os.path.exists(SIMULATOR_ENTRY):
        print("Error: gen_rqc.py or exp_engine.py not found.")
        return

    results_summary = []

    print(f"\n{'Benchmark':<25} | {'Gates':<6} | {'Meas':<6} | {'Valid':<5} | {'Time: Median [Q1, Q3]':<30}")
    print("-" * 90)

    for gates, meas in EXPERIMENTS:
        # 1. Generate Circuit
        gen_cmd = [PYTHON_EXEC, GEN_SCRIPT, str(FIXED_QUBITS), str(gates), str(meas)]
        try:
            subprocess.run(gen_cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, cwd=CURRENT_DIR)
        except subprocess.CalledProcessError as e:
            print(f"Error generating circuit G{gates}M{meas}: {e.stderr.decode()}")
            continue
        
        filename = f"rqc_q{FIXED_QUBITS}_g{gates}_m{meas}.py"
        filepath = os.path.join(RQC_DIR, filename)
        
        if not os.path.exists(filepath):
            print(f"Error: Generated file {filepath} not found.")
            continue

        # 2. Run multiple samples
        valid_times = []
        sys.stdout.write(f"{filename:<25} | {gates:<6} | {meas:<6} | ...")
        sys.stdout.flush()

        for i in range(REPEAT_TIMES):
            run_id = i + 1
            status, val = run_single_benchmark(filename, run_id)
            
            log_result(filename, run_id, status, val)
            
            if status == "SUCCESS":
                valid_times.append(val)
                sys.stdout.write(".")
            elif status == "TIMEOUT":
                sys.stdout.write("T")
            elif status == "LOOPOUT":
                sys.stdout.write("L")
            else:
                sys.stdout.write("E")
            
            sys.stdout.flush()
        
        sys.stdout.write("\r") 
        
        # 3. Statistics Results
        if len(valid_times) > 0:
            median, q1, q3 = calculate_stats(valid_times)
            time_str = f"{median:.3f} [{q1:.3f}, {q3:.3f}]"
            
            print(f"{filename:<25} | {gates:<6} | {meas:<6} | {len(valid_times):<5} | {time_str:<30}")
            
            results_summary.append({
                "name": filename.replace(".py", "").replace("_", "\\_"),
                "qubits": FIXED_QUBITS,
                "gates": gates,
                "meas": meas,
                "median": median,
                "q1": q1,
                "q3": q3
            })
        else:
            print(f"{filename:<25} | {gates:<6} | {meas:<6} | 0     | ALL FAILED (Check Log)            ")

    # 4. Write LaTeX file
    write_latex_file(results_summary)
    
    print(f"Detailed log saved to: {LOG_FILE}")

if __name__ == "__main__":
    main()
